// Code generated by MockGen. DO NOT EDIT.
// Source: processer.go

// Package mock_process is a generated GoMock package.
package mock_process

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProcesser is a mock of Processer interface.
type MockProcesser struct {
	ctrl     *gomock.Controller
	recorder *MockProcesserMockRecorder
}

// MockProcesserMockRecorder is the mock recorder for MockProcesser.
type MockProcesserMockRecorder struct {
	mock *MockProcesser
}

// NewMockProcesser creates a new mock instance.
func NewMockProcesser(ctrl *gomock.Controller) *MockProcesser {
	mock := &MockProcesser{ctrl: ctrl}
	mock.recorder = &MockProcesserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcesser) EXPECT() *MockProcesserMockRecorder {
	return m.recorder
}

// OnRead mocks base method.
func (m *MockProcesser) OnRead(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnRead", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnRead indicates an expected call of OnRead.
func (mr *MockProcesserMockRecorder) OnRead(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRead", reflect.TypeOf((*MockProcesser)(nil).OnRead), data)
}
