// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n ClientOption -f Client -o option.client.go"
// Version: 0.0.3

package gnet

import (
	time "time"

	gnet "github.com/panjf2000/gnet/v2"
	process "github.com/walleframe/walle/process"
	zaplog "github.com/walleframe/walle/zaplog"
)

var _ = walleClient()

// ClientOption
type ClientOptions struct {
	Network string
	// Addr Server Addr
	Addr string
	// Process Options
	ProcessOptions []process.ProcessOption
	// process router
	Router Router
	// frame log
	FrameLogger *zaplog.Logger
	// AutoReconnect auto reconnect server. zero means not reconnect!
	AutoReconnectTime int
	// StopImmediately when session finish,business finish immediately.
	StopImmediately bool
	// WithMulticore sets up multi-cores in gnet server.
	Multicore bool
	// WithLockOSThread sets up LockOSThread mode for I/O event-loops.
	LockOSThread bool
	// WithLoadBalancing sets up the load-balancing algorithm in gnet server.
	LoadBalancing gnet.LoadBalancing
	// WithNumEventLoop sets up NumEventLoop in gnet server.
	NumEventLoop int
	// WithReusePort sets up SO_REUSEPORT socket option.
	ReusePort bool
	// WithTCPKeepAlive sets up the SO_KEEPALIVE socket option with duration.
	TCPKeepAlive time.Duration
	// WithTCPNoDelay enable/disable the TCP_NODELAY socket option.
	TCPNoDelay gnet.TCPSocketOpt
	// WithReadBufferCap sets up ReadBufferCap for reading bytes.
	ReadBufferCap int
	// WithSocketRecvBuffer sets the maximum socket receive buffer in bytes.
	SocketRecvBuffer int
	// WithSocketSendBuffer sets the maximum socket send buffer in bytes.
	SocketSendBuffer int
	// WithTicker indicates that a ticker is set.
	Ticker time.Duration
	// BlockConnect 创建客户端时候，是否阻塞等待链接服务器
	BlockConnect bool
	// Write network data method.
	WriteMethods WriteMethod
	// ReuseReadBuffer 复用read缓存区。影响Process.DispatchFilter.
	// 如果此选项设置为true，在DispatchFilter内如果开启协程，需要手动复制内存。
	// 如果在DispatchFilter内不开启协程，设置为true可以减少内存分配。
	ReuseReadBuffer bool
}

func WithClientOptionNetwork(v string) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.Network
		cc.Network = v
		return WithClientOptionNetwork(previous)
	}
}

// Addr Server Addr
func WithClientOptionAddr(v string) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.Addr
		cc.Addr = v
		return WithClientOptionAddr(previous)
	}
}

// Process Options
func WithClientOptionProcessOptions(v ...process.ProcessOption) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.ProcessOptions
		cc.ProcessOptions = v
		return WithClientOptionProcessOptions(previous...)
	}
}

// process router
func WithClientOptionRouter(v Router) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.Router
		cc.Router = v
		return WithClientOptionRouter(previous)
	}
}

// frame log
func WithClientOptionFrameLogger(v *zaplog.Logger) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.FrameLogger
		cc.FrameLogger = v
		return WithClientOptionFrameLogger(previous)
	}
}

// AutoReconnect auto reconnect server. zero means not reconnect!
func WithClientOptionAutoReconnectTime(v int) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.AutoReconnectTime
		cc.AutoReconnectTime = v
		return WithClientOptionAutoReconnectTime(previous)
	}
}

// StopImmediately when session finish,business finish immediately.
func WithClientOptionStopImmediately(v bool) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.StopImmediately
		cc.StopImmediately = v
		return WithClientOptionStopImmediately(previous)
	}
}

// WithMulticore sets up multi-cores in gnet server.
func WithClientOptionMulticore(v bool) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.Multicore
		cc.Multicore = v
		return WithClientOptionMulticore(previous)
	}
}

// WithLockOSThread sets up LockOSThread mode for I/O event-loops.
func WithClientOptionLockOSThread(v bool) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.LockOSThread
		cc.LockOSThread = v
		return WithClientOptionLockOSThread(previous)
	}
}

// WithLoadBalancing sets up the load-balancing algorithm in gnet server.
func WithClientOptionLoadBalancing(v gnet.LoadBalancing) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.LoadBalancing
		cc.LoadBalancing = v
		return WithClientOptionLoadBalancing(previous)
	}
}

// WithNumEventLoop sets up NumEventLoop in gnet server.
func WithClientOptionNumEventLoop(v int) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.NumEventLoop
		cc.NumEventLoop = v
		return WithClientOptionNumEventLoop(previous)
	}
}

// WithReusePort sets up SO_REUSEPORT socket option.
func WithClientOptionReusePort(v bool) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.ReusePort
		cc.ReusePort = v
		return WithClientOptionReusePort(previous)
	}
}

// WithTCPKeepAlive sets up the SO_KEEPALIVE socket option with duration.
func WithClientOptionTCPKeepAlive(v time.Duration) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.TCPKeepAlive
		cc.TCPKeepAlive = v
		return WithClientOptionTCPKeepAlive(previous)
	}
}

// WithTCPNoDelay enable/disable the TCP_NODELAY socket option.
func WithClientOptionTCPNoDelay(v gnet.TCPSocketOpt) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.TCPNoDelay
		cc.TCPNoDelay = v
		return WithClientOptionTCPNoDelay(previous)
	}
}

// WithReadBufferCap sets up ReadBufferCap for reading bytes.
func WithClientOptionReadBufferCap(v int) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.ReadBufferCap
		cc.ReadBufferCap = v
		return WithClientOptionReadBufferCap(previous)
	}
}

// WithSocketRecvBuffer sets the maximum socket receive buffer in bytes.
func WithClientOptionSocketRecvBuffer(v int) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.SocketRecvBuffer
		cc.SocketRecvBuffer = v
		return WithClientOptionSocketRecvBuffer(previous)
	}
}

// WithSocketSendBuffer sets the maximum socket send buffer in bytes.
func WithClientOptionSocketSendBuffer(v int) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.SocketSendBuffer
		cc.SocketSendBuffer = v
		return WithClientOptionSocketSendBuffer(previous)
	}
}

// WithTicker indicates that a ticker is set.
func WithClientOptionTicker(v time.Duration) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.Ticker
		cc.Ticker = v
		return WithClientOptionTicker(previous)
	}
}

// BlockConnect 创建客户端时候，是否阻塞等待链接服务器
func WithClientOptionBlockConnect(v bool) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.BlockConnect
		cc.BlockConnect = v
		return WithClientOptionBlockConnect(previous)
	}
}

// Write network data method.
func WithClientOptionWriteMethods(v WriteMethod) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.WriteMethods
		cc.WriteMethods = v
		return WithClientOptionWriteMethods(previous)
	}
}

// ReuseReadBuffer 复用read缓存区。影响Process.DispatchFilter.
// 如果此选项设置为true，在DispatchFilter内如果开启协程，需要手动复制内存。
// 如果在DispatchFilter内不开启协程，设置为true可以减少内存分配。
func WithClientOptionReuseReadBuffer(v bool) ClientOption {
	return func(cc *ClientOptions) ClientOption {
		previous := cc.ReuseReadBuffer
		cc.ReuseReadBuffer = v
		return WithClientOptionReuseReadBuffer(previous)
	}
}

// SetOption modify options
func (cc *ClientOptions) SetOption(opt ClientOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *ClientOptions) ApplyOption(opts ...ClientOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *ClientOptions) GetSetOption(opt ClientOption) ClientOption {
	return opt(cc)
}

// ClientOption option define
type ClientOption func(cc *ClientOptions) ClientOption

// NewClientOptions create options instance.
func NewClientOptions(opts ...ClientOption) *ClientOptions {
	cc := newDefaultClientOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogClientOptions != nil {
		watchDogClientOptions(cc)
	}
	return cc
}

// InstallClientOptionsWatchDog install watch dog
func InstallClientOptionsWatchDog(dog func(cc *ClientOptions)) {
	watchDogClientOptions = dog
}

var watchDogClientOptions func(cc *ClientOptions)

// newDefaultClientOptions new option with default value
func newDefaultClientOptions() *ClientOptions {
	cc := &ClientOptions{
		Network:           "tcp",
		Addr:              "localhost:8080",
		ProcessOptions:    nil,
		Router:            nil,
		FrameLogger:       zaplog.GetFrameLogger(),
		AutoReconnectTime: 5,
		StopImmediately:   false,
		Multicore:         false,
		LockOSThread:      false,
		LoadBalancing:     gnet.SourceAddrHash,
		NumEventLoop:      0,
		ReusePort:         false,
		TCPKeepAlive:      0,
		TCPNoDelay:        gnet.TCPNoDelay,
		ReadBufferCap:     0,
		SocketRecvBuffer:  0,
		SocketSendBuffer:  0,
		Ticker:            0,
		BlockConnect:      true,
		WriteMethods:      WriteAsync,
		ReuseReadBuffer:   true,
	}
	return cc
}
