// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: net/packet/packet.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command control command
type Command int32

const (
	// unkown value
	Command_InvalidCommand Command = 0
	// rpc call request
	Command_Request Command = 1
	// rpc call response
	Command_Response Command = 2
	// one way rpc
	Command_Oneway Command = 3
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "InvalidCommand",
		1: "Request",
		2: "Response",
		3: "Oneway",
	}
	Command_value = map[string]int32{
		"InvalidCommand": 0,
		"Request":        1,
		"Response":       2,
		"Oneway":         3,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_net_packet_packet_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_net_packet_packet_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_net_packet_packet_proto_rawDescGZIP(), []int{0}
}

// Flag
type Flag int32

const (
	// nothing
	Flag_Nothing Flag = 0
	// response is error
	Flag_Exception Flag = 1
	// identifies whether client side call is async
	Flag_ClientAsync Flag = 2
)

// Enum value maps for Flag.
var (
	Flag_name = map[int32]string{
		0: "Nothing",
		1: "Exception",
		2: "ClientAsync",
	}
	Flag_value = map[string]int32{
		"Nothing":     0,
		"Exception":   1,
		"ClientAsync": 2,
	}
)

func (x Flag) Enum() *Flag {
	p := new(Flag)
	*p = x
	return p
}

func (x Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_net_packet_packet_proto_enumTypes[1].Descriptor()
}

func (Flag) Type() protoreflect.EnumType {
	return &file_net_packet_packet_proto_enumTypes[1]
}

func (x Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Flag.Descriptor instead.
func (Flag) EnumDescriptor() ([]byte, []int) {
	return file_net_packet_packet_proto_rawDescGZIP(), []int{1}
}

// ErrorCode internal error code
type ErrorCode int32

const (
	// not error
	ErrorCode_NoError ErrorCode = 0
	// unkown error.
	ErrorCode_UnkownErr ErrorCode = 1
	// marshal msg falied
	ErrorCode_MarshalFailed ErrorCode = 2
	// unmarshal msg failed
	ErrorCode_UnmarshalFailed ErrorCode = 3
	// not support interface,not implemented
	ErrorCode_NotSupport ErrorCode = 4
	// timeout
	ErrorCode_Timeout ErrorCode = 5
	// packet size too large
	ErrorCode_PacketTooLarge ErrorCode = 6
	// coding wrong
	ErrorCode_UnexpectedCode ErrorCode = 7
	// session closed
	ErrorCode_SessionClosed ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "NoError",
		1: "UnkownErr",
		2: "MarshalFailed",
		3: "UnmarshalFailed",
		4: "NotSupport",
		5: "Timeout",
		6: "PacketTooLarge",
		7: "UnexpectedCode",
		8: "SessionClosed",
	}
	ErrorCode_value = map[string]int32{
		"NoError":         0,
		"UnkownErr":       1,
		"MarshalFailed":   2,
		"UnmarshalFailed": 3,
		"NotSupport":      4,
		"Timeout":         5,
		"PacketTooLarge":  6,
		"UnexpectedCode":  7,
		"SessionClosed":   8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_net_packet_packet_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_net_packet_packet_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_net_packet_packet_proto_rawDescGZIP(), []int{2}
}

// Packet represent one network packet.
type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// control command
	Cmd int32 `protobuf:"varint,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	// flag
	Flag uint32 `protobuf:"varint,2,opt,name=Flag,proto3" json:"Flag,omitempty"`
	// sequence id
	Sequence uint64 `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	// metadata
	Metadata map[string]string `protobuf:"bytes,4,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// method name
	Uri string `protobuf:"bytes,5,opt,name=Uri,proto3" json:"Uri,omitempty"`
	// reserved request id.
	ReservedRq uint32 `protobuf:"varint,6,opt,name=ReservedRq,proto3" json:"ReservedRq,omitempty"`
	// body
	Body []byte `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	// reserved uint32
	ReservedUint32 uint32 `protobuf:"varint,10,opt,name=ReservedUint32,proto3" json:"ReservedUint32,omitempty"`
	// reserved uint64
	ReservedUint64 uint64 `protobuf:"varint,11,opt,name=ReservedUint64,proto3" json:"ReservedUint64,omitempty"`
	// reserved string
	ReservedString string `protobuf:"bytes,12,opt,name=ReservedString,proto3" json:"ReservedString,omitempty"`
	// reserved bytes
	ReservedBytes []byte `protobuf:"bytes,13,opt,name=ReservedBytes,proto3" json:"ReservedBytes,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_packet_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_net_packet_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_net_packet_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Packet) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *Packet) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Packet) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Packet) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Packet) GetReservedRq() uint32 {
	if x != nil {
		return x.ReservedRq
	}
	return 0
}

func (x *Packet) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Packet) GetReservedUint32() uint32 {
	if x != nil {
		return x.ReservedUint32
	}
	return 0
}

func (x *Packet) GetReservedUint64() uint64 {
	if x != nil {
		return x.ReservedUint64
	}
	return 0
}

func (x *Packet) GetReservedString() string {
	if x != nil {
		return x.ReservedString
	}
	return ""
}

func (x *Packet) GetReservedBytes() []byte {
	if x != nil {
		return x.ReservedBytes
	}
	return nil
}

// ErrorResponse represent rpc call common error
type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// error code
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// logic error
	LogicError bool `protobuf:"varint,2,opt,name=LogicError,proto3" json:"LogicError,omitempty"`
	// desc
	Desc string `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_packet_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_packet_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_net_packet_packet_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetLogicError() bool {
	if x != nil {
		return x.LogicError
	}
	return false
}

func (x *ErrorResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_net_packet_packet_proto protoreflect.FileDescriptor

var file_net_packet_packet_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x22, 0xa5, 0x03, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x43, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x46, 0x6c,
	0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x69, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x69, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x52, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x52, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x26,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64,
	0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x26,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x1a, 0x3b, 0x0a, 0x0d,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x57, 0x0a, 0x0d, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65,
	0x73, 0x63, 0x2a, 0x44, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a,
	0x0e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x4f, 0x6e, 0x65, 0x77, 0x61, 0x79, 0x10, 0x03, 0x2a, 0x33, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67,
	0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x10, 0x02, 0x2a, 0xa7, 0x01,
	0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e,
	0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x6b, 0x6f,
	0x77, 0x6e, 0x45, 0x72, 0x72, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x61, 0x72, 0x73, 0x68,
	0x61, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x6e,
	0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12,
	0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x6f, 0x6f, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x10, 0x06,
	0x12, 0x12, 0x0a, 0x0e, 0x55, 0x6e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x64, 0x65, 0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x64, 0x10, 0x08, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x6f, 0x6e, 0x6d, 0x61, 0x67, 0x69,
	0x2f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_net_packet_packet_proto_rawDescOnce sync.Once
	file_net_packet_packet_proto_rawDescData = file_net_packet_packet_proto_rawDesc
)

func file_net_packet_packet_proto_rawDescGZIP() []byte {
	file_net_packet_packet_proto_rawDescOnce.Do(func() {
		file_net_packet_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_net_packet_packet_proto_rawDescData)
	})
	return file_net_packet_packet_proto_rawDescData
}

var file_net_packet_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_net_packet_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_net_packet_packet_proto_goTypes = []interface{}{
	(Command)(0),          // 0: packet.Command
	(Flag)(0),             // 1: packet.Flag
	(ErrorCode)(0),        // 2: packet.ErrorCode
	(*Packet)(nil),        // 3: packet.Packet
	(*ErrorResponse)(nil), // 4: packet.ErrorResponse
	nil,                   // 5: packet.Packet.MetadataEntry
}
var file_net_packet_packet_proto_depIdxs = []int32{
	5, // 0: packet.Packet.Metadata:type_name -> packet.Packet.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_net_packet_packet_proto_init() }
func file_net_packet_packet_proto_init() {
	if File_net_packet_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_net_packet_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_packet_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_net_packet_packet_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_packet_packet_proto_goTypes,
		DependencyIndexes: file_net_packet_packet_proto_depIdxs,
		EnumInfos:         file_net_packet_packet_proto_enumTypes,
		MessageInfos:      file_net_packet_packet_proto_msgTypes,
	}.Build()
	File_net_packet_packet_proto = out.File
	file_net_packet_packet_proto_rawDesc = nil
	file_net_packet_packet_proto_goTypes = nil
	file_net_packet_packet_proto_depIdxs = nil
}
