// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n InnerOption -f Inner -o option.inner.go"
// Version: 0.0.4

package process

import (
	"context"
	"io"

	"go.uber.org/atomic"
)

var _ = walleProcessInner()

// InnerOption use for process
type InnerOptions struct {
	// Output: write interface(net.Conn)
	Output io.Writer
	// Specify Real Context
	ContextPool ContextPool
	// process context parent
	ParentCtx context.Context
	// Sequence number
	Sequence AtomicNumber
	// load number interface
	Load AtomicNumber
	// bind data
	BindData interface{}
	// process router.
	Router Router
}

// Output: write interface(net.Conn)
func WithInnerOptionOutput(v io.Writer) InnerOption {
	return func(cc *InnerOptions) InnerOption {
		previous := cc.Output
		cc.Output = v
		return WithInnerOptionOutput(previous)
	}
}

// Specify Real Context
func WithInnerOptionContextPool(v ContextPool) InnerOption {
	return func(cc *InnerOptions) InnerOption {
		previous := cc.ContextPool
		cc.ContextPool = v
		return WithInnerOptionContextPool(previous)
	}
}

// process context parent
func WithInnerOptionParentCtx(v context.Context) InnerOption {
	return func(cc *InnerOptions) InnerOption {
		previous := cc.ParentCtx
		cc.ParentCtx = v
		return WithInnerOptionParentCtx(previous)
	}
}

// Sequence number
func WithInnerOptionSequence(v AtomicNumber) InnerOption {
	return func(cc *InnerOptions) InnerOption {
		previous := cc.Sequence
		cc.Sequence = v
		return WithInnerOptionSequence(previous)
	}
}

// load number interface
func WithInnerOptionLoad(v AtomicNumber) InnerOption {
	return func(cc *InnerOptions) InnerOption {
		previous := cc.Load
		cc.Load = v
		return WithInnerOptionLoad(previous)
	}
}

// bind data
func WithInnerOptionBindData(v interface{}) InnerOption {
	return func(cc *InnerOptions) InnerOption {
		previous := cc.BindData
		cc.BindData = v
		return WithInnerOptionBindData(previous)
	}
}

// process router.
func WithInnerOptionRouter(v Router) InnerOption {
	return func(cc *InnerOptions) InnerOption {
		previous := cc.Router
		cc.Router = v
		return WithInnerOptionRouter(previous)
	}
}

// SetOption modify options
func (cc *InnerOptions) SetOption(opt InnerOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *InnerOptions) ApplyOption(opts ...InnerOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *InnerOptions) GetSetOption(opt InnerOption) InnerOption {
	return opt(cc)
}

// InnerOption option define
type InnerOption func(cc *InnerOptions) InnerOption

// NewInnerOptions create options instance.
func NewInnerOptions(opts ...InnerOption) *InnerOptions {
	cc := newDefaultInnerOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogInnerOptions != nil {
		watchDogInnerOptions(cc)
	}
	return cc
}

// InstallInnerOptionsWatchDog install watch dog
func InstallInnerOptionsWatchDog(dog func(cc *InnerOptions)) {
	watchDogInnerOptions = dog
}

var watchDogInnerOptions func(cc *InnerOptions)

// newDefaultInnerOptions new option with default value
func newDefaultInnerOptions() *InnerOptions {
	cc := &InnerOptions{
		Output:      nil,
		ContextPool: WrapContextPool,
		ParentCtx:   context.Background(),
		Sequence:    &atomic.Int64{},
		Load:        &atomic.Int64{},
		BindData:    nil,
		Router:      GetRouter(),
	}
	return cc
}
