// Code generated by "gogen imake"; DO NOT EDIT.
// Exec: "gogen imake . -t=Process -r Process=Processer -o processer.go --merge"
// Version: 0.0.7

package process

// Process 通用process 封装
type Processer interface {
	// OnRead 入口函数。接收数据处理
	OnRead(data []byte) (err error)
}
